### ISSUE TITLE
Use webmanifest for a webapp `suggestion`

### ISSUE THREAD

**Issue by Wjplatformer** [Isaiah08-D/BananaOS#1]
Nowadays, web apps are more popular than `tkinter`, which can be hard to put nice looking elements. Usually apps are built in flutter for mobile. Here is a [reference](https://github.com/dotargz/upsilon-plus). 

> I am not a contributor so can't add *labels*

**Comment by Wjplatformer** [comment]
If you really want to do an appplication for the OS, I suggest you do it using UWA (Universal Windows Applications) with XML code. That way you can bring it up to a standard similar to HTML @Isaiah08-D

**Comment by Isaiah08-D** [comment]
Uhh... Yeah, this was just for fun.
